name: Automerge PRs to master

on:
  workflow_dispatch: {}
  pull_request:
    types: [labeled]
  check_suite:
    types: [completed]

permissions:
  contents: write
  pull-requests: write
  checks: read
  statuses: read

jobs:
  automerge:
    # Ejecuta cuando se añade la etiqueta automerge o cuando todos los checks pasan
    if: >-
      (github.event_name == 'pull_request' && github.event.action == 'labeled' &&
       github.event.label.name == 'automerge') ||
      (github.event_name == 'check_suite' && github.event.check_suite.conclusion == 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Automerge
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mergeMethod: squash
          labels: "automerge"
