name: Automerge PRs to master

on:
  workflow_dispatch: {}
  pull_request:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write
  checks: read
  statuses: read

jobs:
  automerge:
    # Ejecuta únicamente cuando se añade la etiqueta automerge
    if: github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'automerge'
    runs-on: ubuntu-latest
    steps:
      - name: Automerge
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mergeMethod: squash
          labels: "automerge"
