name: Automerge PRs to master

on:
  pull_request:
    types: [labeled, synchronize, opened, reopened]
  check_suite:
    types: [completed]
  workflow_run:
    workflows: ["CI"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write
  checks: read
  statuses: read

jobs:
  automerge:
    # Ejecuta en eventos de PR con base en master, o tras finalizar los checks
    if: >-
      (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master') ||
      (github.event_name != 'pull_request')
    runs-on: ubuntu-latest
    steps:
      - name: Automerge
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mergeMethod: squash
          labels: "automerge"
