name: CI

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 22.13.x

jobs:
  Lint:
    name: Lint-Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.15.0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint

  Type-Check:
    name: Type-Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.15.0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm typecheck

  Unit-Tests:
    name: Unit-Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.15.0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm test:unit

  E2E-Tests:
    name: E2E-Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.15.0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        uses: microsoft/playwright-github-action@v1
      - run: pnpm test:e2e

  Visual-Regression-Tests:
    name: Visual-Regression-Tests
    runs-on: ubuntu-latest
    env:
      PORT: 4321
      BASE_URL: http://127.0.0.1:4321
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.15.0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        uses: microsoft/playwright-github-action@v1
      - name: Build app
        run: pnpm build
      - name: Start server
        run: |
          nohup env PORT=$PORT pnpm start > server.log 2>&1 &
          for i in {1..60}; do
            if curl -fsS "$BASE_URL" >/dev/null; then echo "Server is up"; break; fi
            sleep 2
          done
      - name: Run visual tests
        run: pnpm exec playwright test --config=playwright.visual.config.ts

  Build:
    name: Build-App
    runs-on: ubuntu-latest
    needs:
      - Lint
      - Type-Check
      - Unit-Tests
      - E2E-Tests
      - Visual-Regression-Tests
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.15.0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
