name: Label automerge PRs to master

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

permissions:
  checks: read
  statuses: read
  pull-requests: write
  issues: write

jobs:
  label-automerge:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Add automerge label when all checks pass
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            async function run() {
              const sha = context.payload?.workflow_run?.head_sha;
              if (!sha) return;
              const { data: prs } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: sha
              });
              const targetPr = prs.find(
                (p) => p.state === 'open' && p.base.ref === 'master' && p.head.sha === sha
              );
              if (!targetPr) return;

              if (targetPr.base.ref === 'master') {
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: targetPr.number,
                  labels: ['automerge'],
                });
              }
            }
            run();
