name: Update Visual Snapshots

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to update snapshots for"
        required: true
        default: "enhanced"
        type: choice
        options:
          - enhanced
          - basic

env:
  NODE_VERSION: "22"

jobs:
  update-snapshots:
    name: Update Visual Snapshots
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.14.0

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Build application
        run: pnpm build

      - name: Start application
        run: pnpm preview &
        env:
          PORT: 4321

      - name: Wait for application to be ready
        run: npx wait-on http://localhost:4321

      - name: Update snapshots
        run: |
          if [ "${{ github.event.inputs.environment }}" = "enhanced" ]; then
            pnpm test:visual:enhanced:update
          else
            pnpm test:visual:update
          fi

      - name: Create Pull Request with updated snapshots
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update visual regression snapshots"
          title: "Update visual regression snapshots"
          body: |
            This PR updates the visual regression snapshots for the ${{ github.event.inputs.environment }} environment.

            Changes made:
            - Updated visual regression snapshots
            - Generated by GitHub Actions workflow
          branch: update-snapshots-${{ github.run_id }}
          delete-branch: true
