name: Update Visual Snapshots

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to update snapshots for"
        required: true
        default: "enhanced"
        type: choice
        options: [enhanced, basic]

env:
  NODE_VERSION: "22"
  # Volúmenes con nombre para que los scripts sean idénticos local/CI
  PW_BROWSERS_VOL: ga_pw_browsers
  PW_NODE_MODULES_VOL: ga_pw_node_modules
  PW_STORE_VOL: ga_pw_pnpm_store
  CI: "true"

jobs:
  update-snapshots:
    name: Update Visual Snapshots
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build test image with cache
        run: |
          docker buildx build \
            --cache-from=type=registry,ref=ghcr.io/${{ github.repository }}/erades-com-e2e:cache \
            --cache-to=type=registry,ref=ghcr.io/${{ github.repository }}/erades-com-e2e:cache,mode=max \
            -f Dockerfile.e2e -t erades-com-e2e .

      # Necesitas el build ANTES de que Playwright lance el webServer (preview)
      - name: Build app (inside container)
        run: pnpm run docker:playwright:base -- pnpm build

      # Ejecuta la suite que actualiza snapshots; el webServer lo lanza Playwright según tu config
      - name: Update snapshots (inside container)
        run: |
          if [ "${{ github.event.inputs.environment }}" = "enhanced" ]; then
            pnpm run docker:playwright:base -- pnpm test:visual:enhanced:update
          else
            pnpm run docker:playwright:base -- pnpm test:visual:update
          fi

      - name: Create Pull Request with updated snapshots
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update visual regression snapshots"
          title: "Update visual regression snapshots"
          body: |
            This PR updates the visual regression snapshots for the ${{ github.event.inputs.environment }} environment.
          branch: update-snapshots-${{ github.run_id }}
          delete-branch: true
